package io.kandra.codegen

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.validate

/**
 * KSP processor that generates a type-safe `*Table` object for every `@ScyllaTable` class.
 *
 * For an entity:
 * ```kotlin
 * @ScyllaTable("users")
 * data class User(@PartitionKey val userId: UUID, ...)
 * ```
 *
 * It emits `UserTable.kt` in the same package:
 * ```kotlin
 * // GENERATED BY KANDRA — DO NOT EDIT
 * object UserTable : KandraTable<User> {
 *     val userId = KandraColumnRef<UUID>("user_id")
 *     ...
 * }
 * ```
 */
class KandraProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("io.kandra.core.annotations.ScyllaTable")
        val unprocessed = symbols.filter { !it.validate() }.toList()

        symbols
            .filter { it is KSClassDeclaration && it.validate() }
            .forEach { processClass(it as KSClassDeclaration) }

        return unprocessed
    }

    private fun processClass(classDecl: KSClassDeclaration) {
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()
        val objectName = "${className}Table"

        val properties = classDecl.getAllProperties().toList()

        val columnRefs = properties
            .filter { prop -> !prop.hasAnnotation("io.kandra.core.annotations.Transient") }
            .joinToString("\n    ") { prop ->
                val propName = prop.simpleName.asString()
                val cqlName = resolveCqlName(prop)
                val typeName = resolveTypeName(prop.type.resolve())
                val isLookup = prop.hasAnnotation("io.kandra.core.annotations.LookupIndex")
                if (isLookup) {
                    "val $propName = io.kandra.runtime.dsl.KandraColumnRef<$typeName>(\"$cqlName\", isLookup = true)"
                } else {
                    "val $propName = io.kandra.runtime.dsl.KandraColumnRef<$typeName>(\"$cqlName\")"
                }
            }

        val fileContent = """
// GENERATED BY KANDRA — DO NOT EDIT
package $packageName

object $objectName : io.kandra.runtime.dsl.KandraTable<$className> {
    $columnRefs
}
""".trimIndent()

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, classDecl.containingFile!!),
            packageName = packageName,
            fileName = objectName
        )
        file.write(fileContent.toByteArray())
        file.close()

        logger.info("Kandra codegen: generated $objectName for $className")
    }

    /**
     * Renders a [KSType] as a fully-qualified Kotlin type string, recursing into generic
     * arguments (e.g. `Map<String, String>` -> `kotlin.collections.Map<kotlin.String, kotlin.String>`).
     * A raw qualified name with no arguments is not valid Kotlin for a generic declaration
     * (unlike Java, Kotlin has no raw-type escape hatch), so every type argument must be resolved.
     */
    private fun resolveTypeName(type: KSType): String {
        val qualifiedName = type.declaration.qualifiedName?.asString() ?: "kotlin.Any"
        if (type.arguments.isEmpty()) return qualifiedName
        val argNames = type.arguments.joinToString(", ") { arg ->
            arg.type?.resolve()?.let { resolveTypeName(it) } ?: "*"
        }
        return "$qualifiedName<$argNames>"
    }

    private fun resolveCqlName(prop: KSPropertyDeclaration): String {
        val columnAnnotation = prop.annotations.find {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == "io.kandra.core.annotations.Column"
        }
        if (columnAnnotation != null) {
            val nameArg = columnAnnotation.arguments.find { it.name?.asString() == "name" }
            val value = nameArg?.value as? String
            if (!value.isNullOrBlank()) return value
        }
        return camelToSnake(prop.simpleName.asString())
    }

    private fun camelToSnake(name: String): String =
        name.replace(Regex("([A-Z])")) { "_${it.value.lowercase()}" }.trimStart('_')

    private fun KSPropertyDeclaration.hasAnnotation(fqn: String): Boolean =
        annotations.any { it.annotationType.resolve().declaration.qualifiedName?.asString() == fqn }
}

class KandraProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        KandraProcessor(environment.codeGenerator, environment.logger)
}
