package io.kandra.codegen

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.validate
import io.kandra.core.CqlNaming

/**
 * KSP processor that generates a type-safe `*Table` object for every `@ScyllaTable` class, and —
 * conditionally, only when detected on the *consuming* module's compilation classpath — typed
 * Koin/Kodein DI accessor functions for that same entity.
 *
 * For an entity:
 * ```kotlin
 * @ScyllaTable("users")
 * data class User(@PartitionKey val userId: UUID, ...)
 * ```
 *
 * It emits `UserTable.kt` in the same package:
 * ```kotlin
 * // GENERATED BY KANDRA — DO NOT EDIT
 * object UserTable : KandraTable<User> {
 *     val userId = KandraColumnRef<UUID>("user_id")
 *     ...
 * }
 * ```
 *
 * If `org.koin.core.component.KoinComponent` resolves on this compilation's classpath, it also
 * emits `UserKoinDi.kt`:
 * ```kotlin
 * fun KoinComponent.userRepo(): KandraRepository<User> =
 *     get<KandraRepository<*>>(named("UserRepo")) as KandraRepository<User>
 * fun KoinComponent.userSuspendRepo(): KandraSuspendRepository<User> =
 *     get<KandraSuspendRepository<*>>(named("UserSuspendRepo")) as KandraSuspendRepository<User>
 * ```
 *
 * If `org.kodein.di.DIAware` resolves on this compilation's classpath, it also emits
 * `UserKodeinDi.kt`:
 * ```kotlin
 * fun DIAware.userRepo(): KandraRepository<User> =
 *     direct.instance<KandraRepository<*>>(tag = "User") as KandraRepository<User>
 * fun DIAware.userSuspendRepo(): KandraSuspendRepository<User> =
 *     direct.instance<KandraSuspendRepository<*>>(tag = "UserSuspend") as KandraSuspendRepository<User>
 * ```
 *
 * Detection is purely presence-based (a classpath probe via [Resolver.getClassDeclarationByName]);
 * this module never takes a compile dependency on `koin-core` or `kodein-di` itself — the DI
 * marker types are referenced only as raw fully-qualified strings spliced into generated source,
 * exactly like `kandra-runtime`'s types already are for the `*Table` object. Neither Koin nor
 * Kodein present is the common case (e.g. this repo's own module graph) and is not an error or a
 * warning — it's simply skipped for that entity.
 *
 * The generated qualifier/tag strings are load-bearing: they must match `kandra-koin`'s
 * `Application.kandraKoin()` (`"${'$'}{Entity}Repo"` / `"${'$'}{Entity}SuspendRepo"`) and
 * `kandra-kodein`'s `Application.kandraKodein()` (`"${'$'}{Entity}"` / `"${'$'}{Entity}Suspend"`)
 * exactly, since these accessors exist only to retrieve the exact bindings those files create.
 */
class KandraProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    /**
     * Tracks every `"$packageName.$objectName"` this processor instance has already generated a
     * `*Table.kt` file for, mapped to the qualified name of the entity that claimed it (GH-104).
     *
     * `processClass` derives `objectName` from [KSClassDeclaration.simpleName] alone, never the
     * enclosing class — two distinct `@ScyllaTable` entities nested under different outer types but
     * sharing a simple name (e.g. `Ns1.User` and `Ns2.User`, both in package `com.example.app`) both
     * compute `objectName = "UserTable"`, so both calls to [CodeGenerator.createNewFile] would target
     * the identical virtual file. KSP's own guard against that throws a raw
     * `FileAlreadyExistsException` with no Kandra context — a confusing build crash rather than an
     * actionable diagnostic. This map lets [processClass] detect the collision itself and fail with a
     * clear [KSPLogger.error] instead, before ever calling `createNewFile` a second time.
     *
     * A single [KandraProcessor] instance is reused across every round of one KSP invocation (see
     * [KandraProcessorProvider.create]), so this persists for the lifetime of one compilation — exactly
     * the scope a genuine same-simple-name collision needs to be caught in. Re-processing the *same*
     * entity (identified by its qualified name) across rounds is not treated as a collision.
     */
    private val generatedTableNames = mutableMapOf<String, String>()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("io.kandra.core.annotations.ScyllaTable")
        val unprocessed = symbols.filter { !it.validate() }.toList()

        // Classpath presence probes — resolved once per round, not once per entity. A null result
        // just means that DI framework isn't on this compilation's classpath; that's the normal
        // case, not an error.
        val koinPresent = resolver.getClassDeclarationByName(KOIN_MARKER_FQN) != null
        val kodeinPresent = resolver.getClassDeclarationByName(KODEIN_MARKER_FQN) != null

        symbols
            .filter { it is KSClassDeclaration && it.validate() }
            .forEach { processClass(it as KSClassDeclaration, koinPresent, kodeinPresent) }

        return unprocessed
    }

    private fun processClass(classDecl: KSClassDeclaration, koinPresent: Boolean, kodeinPresent: Boolean) {
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()
        val objectName = "${className}Table"
        val qualifiedName = classDecl.qualifiedName?.asString() ?: "$packageName.$className"

        // GH-109 item 1: containingFile is null for a declaration with no source attached in this
        // KSP round (e.g. a @ScyllaTable class surfaced only from a compiled binary dependency).
        // Dependencies(...) below requires a non-null KSFile, so this used to be an unguarded `!!`
        // — a raw NullPointerException with no Kandra context. Fail with a clear diagnostic instead
        // and skip generation for this entity, rather than crashing the whole build.
        val containingFile = classDecl.containingFile
        if (containingFile == null) {
            logger.error(
                "Kandra codegen: cannot generate a table for '$qualifiedName' — no source file is " +
                    "attached to this declaration in the current compilation round (this typically " +
                    "means @ScyllaTable was found on a class supplied only via a compiled binary " +
                    "dependency, which codegen cannot generate a table for).",
                classDecl
            )
            return
        }

        // GH-104: same-simple-name collision guard. Two distinct entities that compute the same
        // "$packageName/$objectName" (e.g. two differently-nested classes both named "User" in the
        // same package) would otherwise both reach codeGenerator.createNewFile below, and KSP's own
        // duplicate-file guard would crash the build with a raw, un-Kandra-flavored exception. Catch
        // it here instead and fail with a clear diagnostic naming both classes.
        val collisionKey = "$packageName.$objectName"
        val previousOwner = generatedTableNames[collisionKey]
        if (previousOwner != null && previousOwner != qualifiedName) {
            logger.error(
                "Kandra codegen: cannot generate '$objectName' for '$qualifiedName' — that file name is " +
                    "already claimed by '$previousOwner'. Both classes have the simple name '$className' " +
                    "in package '$packageName', and the generated table object/file name is derived only " +
                    "from the simple class name, so they collide. Rename one of the classes, move one to a " +
                    "different package, or give one entity a distinct simple name.",
                classDecl
            )
            return
        }
        generatedTableNames[collisionKey] = qualifiedName

        val properties = classDecl.getAllProperties().toList()

        val columnRefs = properties
            .filter { prop -> !prop.hasAnnotation("io.kandra.core.annotations.Transient") }
            .joinToString("\n    ") { prop ->
                val propName = prop.simpleName.asString()
                val cqlName = resolveCqlName(prop)
                val typeName = resolveTypeName(prop.type.resolve())
                val isLookup = prop.hasAnnotation("io.kandra.core.annotations.LookupIndex")
                if (isLookup) {
                    "val $propName = io.kandra.runtime.dsl.KandraColumnRef<$typeName>(\"$cqlName\", isLookup = true)"
                } else {
                    "val $propName = io.kandra.runtime.dsl.KandraColumnRef<$typeName>(\"$cqlName\")"
                }
            }

        val fileContent = """
// GENERATED BY KANDRA — DO NOT EDIT
package $packageName

object $objectName : io.kandra.runtime.dsl.KandraTable<$className> {
    $columnRefs
}
""".trimIndent()

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, containingFile),
            packageName = packageName,
            fileName = objectName
        )
        file.write(fileContent.toByteArray())
        file.close()

        logger.info("Kandra codegen: generated $objectName for $className")

        if (koinPresent) {
            emitKoinAccessors(packageName, className, containingFile)
        }
        if (kodeinPresent) {
            emitKodeinAccessors(packageName, className, containingFile)
        }
    }

    /**
     * Emits `${className}KoinDi.kt`: typed [org.koin.core.component.KoinComponent] extension
     * functions that wrap the exact `named(...)` qualifier lookups `kandra-koin`'s
     * `Application.kandraKoin()` binds under, so callers get a compile-time-checked accessor
     * instead of hand-typing the qualifier string at every injection site.
     *
     * Referenced Koin types (`KoinComponent`, the `get()`/`named()` extensions) are spliced in as
     * raw fully-qualified strings — this module has no compile dependency on `koin-core`, only the
     * *consuming* module (where this file lands and is compiled) does.
     */
    private fun emitKoinAccessors(
        packageName: String,
        className: String,
        containingFile: KSFile
    ) {
        val entityVar = className.decapitalize()
        val fileName = "${className}KoinDi"

        val fileContent = """
// GENERATED BY KANDRA — DO NOT EDIT
package $packageName

import org.koin.core.component.KoinComponent
import org.koin.core.component.get
import org.koin.core.qualifier.named

@Suppress("UNCHECKED_CAST")
fun KoinComponent.${entityVar}Repo(): io.kandra.runtime.repository.KandraRepository<$className> =
    get<io.kandra.runtime.repository.KandraRepository<*>>(named("${className}Repo")) as io.kandra.runtime.repository.KandraRepository<$className>

@Suppress("UNCHECKED_CAST")
fun KoinComponent.${entityVar}SuspendRepo(): io.kandra.runtime.repository.KandraSuspendRepository<$className> =
    get<io.kandra.runtime.repository.KandraSuspendRepository<*>>(named("${className}SuspendRepo")) as io.kandra.runtime.repository.KandraSuspendRepository<$className>
""".trimIndent()

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, containingFile),
            packageName = packageName,
            fileName = fileName
        )
        file.write(fileContent.toByteArray())
        file.close()

        logger.info("Kandra codegen: generated $fileName (Koin accessors) for $className")
    }

    /**
     * Emits `${className}KodeinDi.kt`: typed [org.kodein.di.DIAware] extension functions that wrap
     * the exact `tag = "..."` lookups `kandra-kodein`'s `Application.kandraKodein()` binds under.
     *
     * Uses `DIAware.direct.instance<T>(tag)` rather than the more commonly seen `by instance(...)`
     * property-delegate form: `DIAware.instance<T>()` returns a `LazyDelegate<T>` meant for `by`
     * property delegation, not a directly usable `T` — an expression-bodied function needs a value,
     * so this goes through `direct` (a [org.kodein.di.DirectDI]) whose `instance<T>()` returns `T`
     * immediately.
     *
     * Referenced Kodein types are spliced in as raw fully-qualified strings — this module has no
     * compile dependency on `kodein-di`, only the *consuming* module does.
     */
    private fun emitKodeinAccessors(
        packageName: String,
        className: String,
        containingFile: KSFile
    ) {
        val entityVar = className.decapitalize()
        val fileName = "${className}KodeinDi"

        val fileContent = """
// GENERATED BY KANDRA — DO NOT EDIT
package $packageName

import org.kodein.di.DIAware
import org.kodein.di.direct
import org.kodein.di.instance

@Suppress("UNCHECKED_CAST")
fun DIAware.${entityVar}Repo(): io.kandra.runtime.repository.KandraRepository<$className> =
    direct.instance<io.kandra.runtime.repository.KandraRepository<*>>(tag = "$className") as io.kandra.runtime.repository.KandraRepository<$className>

@Suppress("UNCHECKED_CAST")
fun DIAware.${entityVar}SuspendRepo(): io.kandra.runtime.repository.KandraSuspendRepository<$className> =
    direct.instance<io.kandra.runtime.repository.KandraSuspendRepository<*>>(tag = "${className}Suspend") as io.kandra.runtime.repository.KandraSuspendRepository<$className>
""".trimIndent()

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, containingFile),
            packageName = packageName,
            fileName = fileName
        )
        file.write(fileContent.toByteArray())
        file.close()

        logger.info("Kandra codegen: generated $fileName (Kodein accessors) for $className")
    }

    /**
     * Renders a [KSType] as a fully-qualified Kotlin type string, recursing into generic
     * arguments (e.g. `Map<String, String>` -> `kotlin.collections.Map<kotlin.String, kotlin.String>`).
     * A raw qualified name with no arguments is not valid Kotlin for a generic declaration
     * (unlike Java, Kotlin has no raw-type escape hatch), so every type argument must be resolved.
     *
     * GH-36: also appends `?` when [KSType.isMarkedNullable] is true, at every nesting level (a
     * nullable type argument, e.g. `List<String?>`, is resolved the same way since each argument is
     * itself a recursive [resolveTypeName] call on its own resolved [KSType]) — so `String` and
     * `String?` properties now generate distinct `KandraColumnRef<kotlin.String>` /
     * `KandraColumnRef<kotlin.String?>` declarations instead of erasing the difference.
     *
     * `KandraColumnRef<T>` (`kandra-runtime`'s `dsl/QueryDsl.kt`) declares `T` with no upper bound,
     * which defaults to Kotlin's implicit `Any?` — so a nullable type argument like
     * `KandraColumnRef<kotlin.String?>` is ordinary, valid Kotlin generic syntax. That means full
     * nullability threading is achievable by rendering it into the type argument itself, with no
     * change needed to `KandraColumnRef`'s own definition (out of scope for this fix — see ISS-052).
     */
    private fun resolveTypeName(type: KSType): String {
        val qualifiedName = type.declaration.qualifiedName?.asString() ?: "kotlin.Any"
        val nullabilitySuffix = if (type.isMarkedNullable) "?" else ""
        if (type.arguments.isEmpty()) return "$qualifiedName$nullabilitySuffix"
        val argNames = type.arguments.joinToString(", ") { arg ->
            arg.type?.resolve()?.let { resolveTypeName(it) } ?: "*"
        }
        return "$qualifiedName<$argNames>$nullabilitySuffix"
    }

    /**
     * Delegates to [CqlNaming.resolveColumnName] (kandra-core) so this compile-time resolution
     * stays IDENTICAL to `SchemaRegistry`'s runtime resolution — see GH-30. Previously this method
     * re-implemented the blank-name fallback independently, which meant a `@Column("")` field could
     * resolve to a different cqlName here than in the runtime schema for the very same entity.
     */
    private fun resolveCqlName(prop: KSPropertyDeclaration): String {
        val columnAnnotation = prop.annotations.find {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == "io.kandra.core.annotations.Column"
        }
        val columnName = columnAnnotation?.arguments
            ?.find { it.name?.asString() == "name" }
            ?.value as? String
        return CqlNaming.resolveColumnName(columnName, prop.simpleName.asString())
    }

    private fun String.decapitalize(): String =
        replaceFirstChar { it.lowercase() }

    private fun KSPropertyDeclaration.hasAnnotation(fqn: String): Boolean =
        annotations.any { it.annotationType.resolve().declaration.qualifiedName?.asString() == fqn }

    private companion object {
        const val KOIN_MARKER_FQN = "org.koin.core.component.KoinComponent"
        const val KODEIN_MARKER_FQN = "org.kodein.di.DIAware"
    }
}

class KandraProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        KandraProcessor(environment.codeGenerator, environment.logger)
}
